kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: influxdb
    project: twittergraph
  name: influxdb
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
